# Generated by Django 2.1.2 on 2018-10-07 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=60, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('cell', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='track',
            name='c_address',
            field=models.CharField(max_length=250, verbose_name='Complainant Address'),
        ),
        migrations.AlterField(
            model_name='track',
            name='c_name',
            field=models.CharField(max_length=100, verbose_name='Complainant Name'),
        ),
        migrations.AlterField(
            model_name='track',
            name='r_from',
            field=models.CharField(max_length=100, verbose_name='Received From'),
        ),
        migrations.AlterField(
            model_name='track',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracks.Sender'),
        ),
    ]
