# Generated by Django 2.1.2 on 2018-10-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20181007_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='r_from',
        ),
    ]
