# Generated by Django 2.1.2 on 2018-10-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_track_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-updated']},
        ),
        migrations.RenameField(
            model_name='track',
            old_name='remarks',
            new_name='action_required',
        ),
        migrations.AddField(
            model_name='track',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
